### PR TITLE
Add metadata descriptions, fix blinking link, add custom 404 page

### PR DESCRIPTION
**Pull request by kevin-zou**
### Metadata
Ben sent me a screenshot of the preview for our apply page being wonky. From Google I suspect it might be something to do with our CDN. This is an attempt to see if it will fix it, but it's updating the metadata anyways.
image

### Fix blinking link
This is regarding the "Application Closed/Open" link in the nav bar. On default it loads in as default and appears to be in the "Closed" state, but once the proper value is read from firestore it will go to the "Open" state. You can most clearly see this if you click on the nwPlus icon repeatedly. Waiting for firestore to return before rendering this link fixes the problem. We also added a fade in effect that triggers when the firestore data populates.

### Custom 404 page
When we were setting up Firebase I think we used [rewrites](https://firebase.google.com/docs/hosting/full-config). Rewrites allow you to control navigation and our current configuration makes it so that any link that isn't matched will fall back to `index.html` (SPA behaviour). By changing this configuration it should use our new 404 page.

image

image

### CODE REVIEW

**Review by ianmah — COMMENTED** [review]
So we're attempting to trigger a metadata cache update right? sounds good, if that doesn't work is there any setting on cloudflare to refresh the cache or anything? Might have cached a 503 and is now displaying that as a preview.

**Review by ianmah — COMMENTED** [review]
Is this the expected 404 page? https://nwplus-io--pr119-metadata-ui0x0hyn.web.app/asd 
image

**Comment by kevin-zou** [comment]
Yup! Hoping that this will just trigger it, but if not then it's probably something that we have to do in Cloudflare like you said.

> Is this the expected 404 page?
This page is expected, but now that I think about it I'm wondering if it's what we desire... Redirecting to the index on a missing page  makes sense, but it seemed weird that something like `nwplus.io/bad-url` would lead to a working page. What do you think of this? Maybe could also add a custom 404 page if design has time for that

**Comment by ianmah** [comment]
lets ask design @kevin-zou

**Comment by ianmah** [comment]
The application open thingy still 'blinks' once the firebase thing loads, could we add some kind of simple fade in animation?

**Review by ianmah — APPROVED** [review]
Beautyyyyy

**Comment by kevin-zou** [comment]
stonks 📈

**Pull request merged**
