### PR TITLE
Update hackcamp card

### PR DESCRIPTION
**Pull request by samanthatuhseng**
## Description

#170 
Screenshot 2023-09-19 at 3 42 56 PM

## Other considerations

Since there isnt a design specific for the preview card, I took the image from the dev figma and sliced a portion of the mobile design into it. Let me know if theres any changes that is needed.

### CODE REVIEW

**Review by michelleykim — COMMENTED** [review]
ooh looking good! I just realized that there was an added comment that I forgot to update ticket with. Can you change the copy from "Registration Closed" to “Registration Opens: October 6”?

**Comment by samanthatuhseng** [comment]
Screenshot 2023-09-19 at 6 38 54 PM

**Comment by samanthatuhseng** [comment]
Screenshot 2023-09-19 at 10 21 20 PM

**Review by michelleykim — APPROVED** [review]
lgtm!

**Review by meleongg — APPROVED** [review]
lgtm! can't tell if it's just me but is the HC card shifted a bit to the left?

**Pull request merged**
