### PR TITLE
Opened registeration

### PR DESCRIPTION
**Pull request by DonaldKLee**
image

### CODE REVIEW

**Comment by naijwu** [comment]
@DonaldKLee try to pull an image from the cmd-f figma

**Comment by DonaldKLee** [comment]
> @DonaldKLee try to pull an image from the cmd-f figma

Oops just saw this! Will ask design for the graphic, can't find it on figma

**Comment by DonaldKLee** [comment]
> @DonaldKLee try to pull an image from the cmd-f figma

added!

**Review by naijwu — APPROVED** [review]
mint

**Pull request closed without merging**
