### PR TITLE
Updated Martin's headshot

### PR DESCRIPTION
**Pull request by DonaldKLee**

### CODE REVIEW

**Review by meleongg — APPROVED** [review]
lgtm but we really gotta standardize the image sizes 💀 

wait a sec I think Donald updated the node versions

**Comment by DonaldKLee** [comment]
> lgtm but we really gotta standardize the image sizes 💀
> 
> wait a sec I think Donald updated the node versions

Oops.... I did a npm i cause i was missing modules or smt

**Review by meleongg — COMMENTED** [review]
smt wrong with npm stuff, prolly need jae wu to explain

**Comment by naijwu** [comment]
instead of doing npm, try using npm ci -- bypasses the package.json and uses the lockfile to ensure completely completely reproducible builds

also, adding the use Node 16.x might be necessary for this project as well (but not sure)

id just start from the beginning again, though (just look at how much this commit changes in insertions/deletions). package errors suck

**Pull request closed without merging**
